# Generated by Django 2.2 on 2020-01-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200103_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('SIP', 'SIP'), ('LS', 'LumpSum')], max_length=3)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
            ],
        ),
    ]
